### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by wzzjhc** [gyxuehu/EwoMail#13]
This is the mail system at host mail.glodluck8.com.

发送自 MAILER-DAEMON@mail.glodluck8.com
我是新安装的，每次发送邮件给别人时，都会收到这样子的一个发送失败的提示邮件，
我使用的是linode服务器，但是我又是可以收到邮件的。

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

**Comment by gyxuehu** [comment]
这些信息不够详细，要把后面的贴出来才清楚，应该是你的25端口被禁用导致的
