### ISSUE TITLE
debian上无法使用安装脚本安装

### ISSUE THREAD

**Issue by MasterLivens** [gyxuehu/EwoMail#15]
./start.sh: line 16: setenforce: command not found
./start.sh: line 145: rpm: command not found
./start.sh: line 150: yum: command not found
cp: cannot create regular file '/etc/yum.repos.d/epel-6.repo': No such file or directory
./start.sh: line 152: yum: command not found
./start.sh: line 155: rpm: command not found
./start.sh: line 158: [: =: unary operator expected
./start.sh: line 161: rpm: command not found
ewomail-lamp install failed

**Comment by gyxuehu** [comment]
暂时只支持 centos6/7的安装
