### ISSUE TITLE
ClamAV update too slow

### ISSUE THREAD

**Issue by Archerkong** [gyxuehu/EwoMail#19]
i had waited more than 665s ,download data about 1774.59KiB/109.47M

ClamAV update process started at Mon Nov 30 21:35:59 2020
daily database available for download (remote version: 26003)
WARNING: Download failed (56) WARNING:  Message: Failure when receiving data from the peer
WARNING: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Trying again in 5 secs...
daily database available for download (remote version: 26003)

The problem is how can i download it faster?and i had use the problem resolve http://doc.ewomail.com/docs/ewomail/install ,when ia press ctrl+c it will show fail
and i try some times,now sometime will be failed ,why does is happened?

**Comment by gyxuehu** [comment]
The network of your server can't download the feature library from ClamAV. It is recommended that you use centos8 to install. Centos8 will not have this problem again

**Comment by Archerkong** [comment]
> The network of your server can't download the feature library from ClamAV. It is recommended that you use centos8 to install. Centos8 will not have this problem again

really?i will try it later,thanks
