### ISSUE TITLE
ewomail-lamp install failed

### ISSUE THREAD

**Issue by CiaoFox** [gyxuehu/EwoMail#2]
纯净centos7环境，最后报错..请问为什么呢	
file /usr/lib64/libltdl.so.7 from install of ewomail-lamp-1.0-el6.x86_64 conflicts with file from package libtool-ltdl-2.4.2-22.el7_3.x86_64
ewomail-lamp install failed

**Comment by shanguanyunya** [comment]
yum remove libtool-ltdl* -y
