### ISSUE TITLE
可以手动升级rainloop版本吗

### ISSUE THREAD

**Issue by HenryRou** [gyxuehu/EwoMail#20]
可以的话，能留个方法不
自己手动更新webmail版本会出现domain is not allowed，然后管理界面的密码也没有跟数据库同步

**Comment by gyxuehu** [comment]
升级后的管理界面的密码就不同步后台了，用官网的默认密码就可以了。

**Comment by HenryRou** [comment]
问题是，不止管理界面的密码，连在账户里面改密码都不行了，还要添加一个domain，不然domain is not allowed，所以想来问问作者改的rainloop要改哪里才能接入数据库

**Comment by HenryRou** [comment]
> 升级后的管理界面的密码就不同步后台了，用官网的默认密码就可以了。

问题是，不止管理界面的密码，连在账户里面改密码都不行了，还要添加一个domain，不然domain is not allowed，所以想来问问作者改的rainloop要改哪里才能接入数据库。
