### ISSUE TITLE
请问怎么直接域名访问，帮端口去掉比如 mail.xxxx.com 访问webmail页面

### ISSUE THREAD

**Issue by HankMo** [gyxuehu/EwoMail#26]
请问怎么直接域名访问，帮端口去掉比如 mail.xxxx.com 访问webmail页面

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/135092078-6fd28f41-7138-4ba3-b3c9-ddc783a727e9.png)
我按照这个操作还是不行 去掉端口打不开网页，

**Comment by gyxuehu** [comment]
这个文件位置不用修改。

修改Nginx配置的这2个文件就可以了，修改完后重启nginx，然后打开webmail就可以了
/ewomail/nginx/conf/vhost/rainloop.conf
/ewomail/nginx/conf/vhost/rainloop-ssl.conf


如需及时处理的可联系邮箱地址：solve@ewomail.cn
