### ISSUE TITLE
ewomail 在发送附件的时候，有时候收到的附件打不开，提示内容缺失，

### ISSUE THREAD

**Issue by QinQiang666** [gyxuehu/EwoMail#3]
你好，我在使用ewomail 发送邮件附件的时候，收件人收到附件后打不开附件，提示附件内容缺少，查看文件大小是比正常文件小 0.1k 。这个是什么问题那？从发件人已发邮件中查看附件是没有问题的。

**Comment by gyxuehu** [comment]
使用的是什么客户端，服务器配置较低的情况下，参考文档关闭杀毒软件

**Comment by QinQiang666** [comment]
> 使用的是什么客户端，服务器配置较低的情况下，参考文档关闭杀毒软件

**Comment by QinQiang666** [comment]
使用的 forxmail 客户端，邮件服务器配置是：centos7.4 2C4G

**Comment by gyxuehu** [comment]
这种情况，你可以更换其他发件客户端，发送到其他邮局，进行测试。
每个邮局都会对附件进行杀毒检查，不符合规则的就会过滤，可自行多测试。
