### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by weiyuchen** [gyxuehu/EwoMail#4]
您好，我已经在内网环境里搭建了这个邮件服务器体系，但是在管理页面添加邮箱后， 没有办法在web端进行登陆，利用foxmail倒是能够登录，不太明白其中的原因，http://IP:8000端口登录的时候显示“无法连接到服务器”

**Comment by weiyuchen** [comment]
![can't connect](D:\Entrance\workdir\2019\month1-3\docker-honeypot\Mail-honeypot\ewomail-bug.PNG)

**Comment by gyxuehu** [comment]
可以尝试在服务器系统加hosts
http://doc.ewomail.com/docs/ewomail/local_con

**Comment by weiyuchen** [comment]
问题已经解决了，感谢@gyxuehu，在服务器系统上修改hosts文件即可

**Comment by LoongLiWang** [comment]
你好，我的问题你和一样，foxmail可以登陆，但是web版本的无法登陆，在进行服务器添加hosts之后依旧是这个问题，请问，还有其他会导致此问题的原因么？

**Comment by LoongLiWang** [comment]
哦，了解了，这个hosts配置，必须要和邮箱系统设置保持一致
